services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:8080"
    ports:
      - "8081:8081"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik:/etc/traefik

  webapp:
    build:
      context: . # Construire depuis le répertoire actuel
      dockerfile: Dockerfile
    container_name: webapp
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.webapp.rule=Host(`ch.musubi.dev`)"
      - "traefik.http.services.webapp.loadbalancer.server.port=8000"
    volumes:
      - .:/app
