version: '3.9'

services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    command:
      - "--api.insecure=true" # Activer l'interface web pour tester
      - "--providers.docker=true" # Utiliser Docker comme fournisseur
      - "--entrypoints.web.address=:80" # Configurer le port 80
    ports:
      - "80:80"       # Exposer le port HTTP
      - "8080:8080"   # Exposer le tableau de bord Traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Nécessaire pour gérer Docker
      - ./traefik:/etc/traefik # Configuration statique (facultatif)

  webapp:
    image: nom_de_votre_image # Remplacez par l'image de votre site
    container_name: webapp
    labels:
      - "traefik.enable=true" # Activer Traefik pour ce service
      - "traefik.http.routers.webapp.rule=Host(`ch.musubi.dev`)" # Nom de domaine
      - "traefik.http.services.webapp.loadbalancer.server.port=8000" # Port interne exposé par l'application
    volumes:
      - .:/app
