services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    command:
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--providers.docker=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=admin@votre-domaine.com"
      - "--certificatesresolvers.myresolver.acme.storage=/etc/traefik/acme.json"
      - "--api.insecure=true"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/acme.json:/etc/traefik/acme.json
    networks:
      - web

  webapp:
    image: python:3.10-slim
    container_name: webapp
    working_dir: /app
    volumes:
      - ./webapp:/app
    command: ["sh", "-c", "pip install flask && python app.py"]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.webapp.rule=Host(`votre-domaine.com`)"
      - "traefik.http.routers.webapp.entrypoints=websecure"
      - "traefik.http.routers.webapp.tls=true"
      - "traefik.http.routers.webapp.tls.certresolver=myresolver"
    networks:
      - web

networks:
  web:
    driver: bridge
